POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "probando delete",
    "author": "balta",
    "url": "boca.com",
    "likes": 10
}

###
GET http://localhost:3001/api/blogs


###
DELETE http://localhost:3001/api/blogs/67852ece132a41f9bd3b9a25


###
PUT http://localhost:3001/api/blogs/678527204fed24cd3d6e2f25
Content-Type: application/json

{
    "title": "probando put",
    "author": "baltasar",
    "url": "boca.com",
    "likes": 12
}