POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "segundo post",
    "author": "balta",
    "url": "boca.com",
    "likes": 12
}

###
GET http://localhost:3001/api/blogs
